apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: mockbank
data:
  init-db.sql: |
    CREATE DATABASE transaction_db;
    CREATE DATABASE notification_db;
    GRANT ALL PRIVILEGES ON DATABASE account_db TO mockbank;
    GRANT ALL PRIVILEGES ON DATABASE transaction_db TO mockbank;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO mockbank;
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mockbank
type: Opaque
stringData:
  POSTGRES_USER: mockbank
  POSTGRES_PASSWORD: mockbank123
  POSTGRES_DB: account_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mockbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "mockbank"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mockbank
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
